// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxXDdSps4s6f-fJz63V9v6HBtt7HDh9rA',
    appId: '1:914207723010:web:5dcebdc8899adf7776611b',
    messagingSenderId: '914207723010',
    projectId: 'campusconnect-2d644',
    authDomain: 'campusconnect-2d644.firebaseapp.com',
    storageBucket: 'campusconnect-2d644.firebasestorage.app',
    measurementId: 'G-CCLEXDX3ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbIcpt3YiT0kTvlbDU2lkWVI6OYmFBgzQ',
    appId: '1:914207723010:android:bd72b09786feeae776611b',
    messagingSenderId: '914207723010',
    projectId: 'campusconnect-2d644',
    storageBucket: 'campusconnect-2d644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjWuidRc80YKsNT4qDFZeMaI5GA--4Zb4',
    appId: '1:914207723010:ios:a6c7eb811abf8b2776611b',
    messagingSenderId: '914207723010',
    projectId: 'campusconnect-2d644',
    storageBucket: 'campusconnect-2d644.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjWuidRc80YKsNT4qDFZeMaI5GA--4Zb4',
    appId: '1:914207723010:ios:a6c7eb811abf8b2776611b',
    messagingSenderId: '914207723010',
    projectId: 'campusconnect-2d644',
    storageBucket: 'campusconnect-2d644.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxXDdSps4s6f-fJz63V9v6HBtt7HDh9rA',
    appId: '1:914207723010:web:07736c2a189ad85e76611b',
    messagingSenderId: '914207723010',
    projectId: 'campusconnect-2d644',
    authDomain: 'campusconnect-2d644.firebaseapp.com',
    storageBucket: 'campusconnect-2d644.firebasestorage.app',
    measurementId: 'G-KCBYCMHCC3',
  );
}
